name: Build and Publish Plugin
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
      name: Build and Publish Plugin
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            ref: master
          
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 17
            cache: 'gradle'

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - name: Export Properties
          run: |
            PROPERTIES="$(./gradlew properties --console=plain -q)"
            echo "version=$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')" >> $GITHUB_ENV
            echo "name=$(echo "$PROPERTIES" | grep "^pluginName:" | cut -f2- -d ' ')" >> $GITHUB_ENV
            
        - name: Patch Changelog
          run: ./gradlew patchChangelog

        - name: Build Plugin
          run: ./gradlew buildPlugin

        - name: Output Release Notes
          run: |
            echo "# 🚀 Tagged Release 🚀" >> $GITHUB_STEP_SUMMARY
            RELEASE_NOTES="$(./gradlew getChangelog --console=plain -q)"
            DELIMITER="$(openssl rand -hex 8)"

            echo "release_notes<<$DELIMITER" >> $GITHUB_ENV
            echo "$RELEASE_NOTES" >> $GITHUB_ENV
            echo "$DELIMITER" >> $GITHUB_ENV

            echo "$RELEASE_NOTES" >> $GITHUB_STEP_SUMMARY

        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            automatic_release_tag: latest
            files: |
              *.jar
        
        - name: Commit Release Notes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Docs: Update Changelog"
            branch: main
            file_pattern: ./github/CHANGELOG.md
      
    
