name: Build and Publish Plugin
on:
  push:
    branches: master
jobs:
  build:
      name: Build Plugin
      runs-on: ubuntu-latest
      steps:
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 17
            cache: 'gradle'

        - name: Export Properties
          run: |
            PROPERTIES="$(./gradlew properties --console=plain -q)"
            echo "version=$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')" >> $GITHUB_ENV
            echo "name=$(echo "$PROPERTIES" | grep "^pluginName:" | cut -f2- -d ' ')" >> $GITHUB_ENV
            
        - name: Patch Changelog
          run: ./gradlew patchChangelog

        - name: Build Plugin
          run: ./gradlew buildPlugin
          
  publish:
      runs-on: ubuntu-latest
      name: Publish Plugin
      steps:
      - name: Output Release Notes
        run: |
            echo "# 🚀 Tagged Release 🚀" >> $GITHUB_STEP_SUMMARY
            RELEASE_NOTES="$(./gradlew getChangelog --console=plain -q)"
            DELIMITER="$(openssl rand -hex 8)"

            echo "release_notes<<$DELIMITER" >> $GITHUB_ENV
            echo "$RELEASE_NOTES" >> $GITHUB_ENV
            echo "$DELIMITER" >> $GITHUB_ENV

            echo "$RELEASE_NOTES" >> $GITHUB_STEP_SUMMARY
      
      - name: Publish to Marketplace
        env: 
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/*.jar
          body: ${{ env.release_notes }}
          draft: true
        
      - name: Commit Release Notes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Docs: Update Changelog"
          branch: main
          file_pattern: ./github/CHANGELOG.md
    
