name: Build and Publish Plugin
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and Publish Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: zulu
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create Release Notes
      - id: create_release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Export Properties
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          echo "version=${{ steps.create_release.outputs.resolved_version }}" >> $GITHUB_ENV
          echo "name=$(echo "$PROPERTIES" | grep "^pluginName:" | cut -f2- -d ' ')" >> $GITHUB_ENV

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Patch Changelog
        run: ./gradlew patchChangelog --release-note= ${{ steps.create_release.outputs.body }}

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: 'build/libs/*.jar'
          bodyFile: '.github/CHANGELOG.md'
    
