name: Build and Publish Plugin
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
      name: Build and Publish Plugin
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            ref: master
          
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: zulu
            java-version: 17
            cache: 'gradle'

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - name: Export Properties
          run: |
            PROPERTIES="$(./gradlew properties --console=plain -q)"
            echo "version=$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')" >> $GITHUB_ENV
            echo "name=$(echo "$PROPERTIES" | grep "^pluginName:" | cut -f2- -d ' ')" >> $GITHUB_ENV
            
        - name: Patch Changelog
          run: ./gradlew patchChangelog

        - name: Build Plugin
          run: ./gradlew buildPlugin

        - uses: release-drafter/release-drafter@v6
          with:
            config-name: configs/release-drafter.yml
            version: ${{ env.VERSION }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Commit Release Notes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Docs: Update Changelog"
            branch: main
            file_pattern: ./github/CHANGELOG.md
      
    
